### ISSUE TITLE
Internal error when changing password

### ISSUE THREAD

**Issue by ar-anvd** [poetapp/explorer-web#628]
Example pass: 

qA[:"6Rw8$(aNuKs

**Comment by lautarodragan** [comment]
Should be working now. Can you confirm @ar-anvd?

**Comment by ar-anvd** [comment]
@lautarodragan this is still broken for me when changing password and when creating a new account.
